name: On push, deploying to Test
on: [push]
jobs:
#  checkout:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-py-2-3-build-deploy.yml@common-workflows
    with:
      process_env: Test
    secrets: inherit
