name: Release Deploy to prod
on:
  release:
    types: [published]
jobs:
  checkout-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  run-main:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      process_env: Prod
