name: On Release, deploying to Prod
on:
  release:
    types: [published]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  run-build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      process_env: Prod
    secrets: inherit
